version: '3.5'

services:
  cakephp-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: cakephp-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
  mysql-adminer :
    depends_on:
      - mysql-db
    image : adminer
    ports :
      - 8080:8080
