version: '3.5'

services:
  allwishesngreetingimages:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: allwishesngreetingimages
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
  allwishesngreetingimages-db:
    image: mysql:5.7
    container_name: allwishesngreetingimages-db
    volumes:
      - ./_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=allwishesngreetingimages
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=master
  mysql-adminer :
    depends_on:
      - allwishesngreetingimages-db
    image : adminer
    ports :
      - 8080:8080
